GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTU4ODg5NDkwMywiZXhwIjoxNTg4ODk0OTE4fQ.VzHtmztGzcdvR4Gz_tI5u0FANJoDIvY0dBdCAgTjNmo

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTU4ODg5NDg1OX0.FePrrwVSk6xwVunptuiNluxtpCMncEVYwNGmCZmLh_Q"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "kyle"
}
###
DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTU4ODg5NDg1OX0.FePrrwVSk6xwVunptuiNluxtpCMncEVYwNGmCZmLh_Q"
}